{
    "correlationUUID": "9f53fea6-c288-4d19-8d85-93832294f21a",
    "commonHeader": {
        "timestamp": "2020-07-20T18:15:21.593Z",
        "originatorId": "System",
        "requestId": "remote-python-connection-fail",
        "subRequestId": "1",
        "flags": null
    },
    "actionIdentifiers": {
        "blueprintName": "RT-remote-python",
        "blueprintVersion": "1.0.0",
        "actionName": "connection-fail",
        "mode": "sync"
    },
    "status": {
        "code": 500,
        "eventType": "EVENT_COMPONENT_FAILURE",
        "timestamp": "2020-07-20T18:15:22.846Z",
        "errorMessage": "FAILURE : prepare-env : Command failed during env. preparation... timeout(120) requestId (remote-python-connection-fail). grpcError: (Connection refused: /127.0.0.1:4242)",
        "message": "failure"
    },
    "payload": {
        "connection-fail-response": {
            "execute-command-payload": "",
            "execute-command-logs": ""
        }
    }
}
